### ISSUE TITLE
Erik Project 2

### ISSUE THREAD

**Issue by erikslewis** [ga-wdi-pvd/project2-gallery#11]
Made a crud fitness apps has a few bugs still.
https://erikslewis.github.io./   Portfolio Link, still need work 

https://github.com/erikslewis/Project-2-PT/tree/pre-devise   link to Crud App repo

**Comment by estermer** [comment]
Scoring 0 - 3
Your Score 2

Erik,

I am really impressed with this app you made.

When you showed me this I was blown away at your integration of the Spotify API to add something shnazy to your app.

Over all the user flow and design could be better, but that can always be left up to someone else in the real world. I personally am not a design guy, so no worries. You put your personal spin on it and I like that.

You had way more models than what was required for this projects so you went above and beyond, and your code was well organized by taking advantage of the Rails way.

You are correct though there are a few bugs, you just need to work them out. 

The other thing you need to make sure is that you write some comments in your code if it is taken from someone else. Tiny functions you don't need to reference, but make sure you reference your Spotify Functionality if you did not write it yourself.

Otherwise, Great Job on this project, looking forward to seeing your contribution to project 3!

-Eric
