### ISSUE TITLE
Neil's Project#2

### ISSUE THREAD

**Issue by neilburd** [ga-wdi-pvd/project2-gallery#5]
Here is the app Deployed on Heroku
https://timekeypr.herokuapp.com/

Here is the gitHub repo of the project.
https://github.com/neilburd/Project-2-timeKeeper

Here is the project in my "portfolio" (this portfolio will be changing soon now that I know the magic of materialize.)
https://neilburd.github.io/portfolio/

**Comment by estermer** [comment]
Scoring 0 - 3
Your Score: 3

Neil, Great job with this one.

You took advantage of a css library in order to no reinvent the wheel on styling, and yet you organized your application well.

Your Code looks clean, and for the most part, took advantage of Rails very nicely.

You have 3 models, including a user which can be authenticated using devise which is above the requirements for this project. So great job.

The flow of your user experience could be a little better. Definitely in the future if you have time to think through how to get good user experience from making one view to the next.

Overall You did a great job. Keep it up and looking forward to seeing what you and your team will accomplish for project 3.

-Eric
