### ISSUE TITLE
Sandy Pok - Project 2

### ISSUE THREAD

**Issue by SandyPok** [ga-wdi-pvd/project2-gallery#9]

**Comment by SandyPok** [comment]
[My 2nd Project](https://myfitnesstracker.herokuapp.com/)

[Github Profile](https://github.com/SandyPok)

**Comment by tvcrawley** [comment]
# Project Evaluation

| Category                        | Incomplete    ☹️                            | Progressing  👍                             | Performing        ✅                        | Excelling         😃                        |
| ------------------------------- | ---------------------------------------- | ---------------------------------------- | ---------------------------------------- | ---------------------------------------- |
| Technical Requirements          |  |  | The app contains 2 models, with at least 1 association. At least 1 model is full CRUD. |  |
| Creativity and Interface        |  | The app is styled and has an interface of value to the end user: it is not just a nav bar and an index page. |  |  |
| Code Quality                    |       |  | Code is well-formatted, well-named, and contains few style / quality issues. |  |
| Functionality    |  |  | Application contains no major errors. |   |
| Planning / Process / Submission | No submission received, or submission does not contain basic documentation of planning (ERD, wireframes, commit history, etc). |  |  |  |

**Comment by tvcrawley** [comment]
@SandyPok Function-wise your application is good. Since scaffolding was used, I hope you know what the files and code that were created are doing for you. 

On revisiting, adding in the process you had for planning would be great (ERD, wireframes, etc) as well as adding to the readme the explanations asked for in the [project 2 repo](https://github.com/ga-wdi-pvd/project2). 
Additionally, validating your code! There were a few errors in your CSS.

_This project was accessed using the [evaluation](https://github.com/ga-wdi-pvd/project2/blob/master/evaluation.md) included in the project 2 repo._

**Comment by SandyPok** [comment]
Toni,

Sorry I did created an ERD and wireframe. That was the first step taken. Can I go back and include it?

Thank You,

Sandy Pok

**Comment by tvcrawley** [comment]
Yes, go ahead.
